package mc.monacotelecom.tecrep.equipments.enums;

public enum Status {
    INSTORE, AVAILABLE, BOOKED, ASSIGNED, ACTIVATED, ONHOLD, RETURNED, NOTRETURNED, DEPRECATED, REPACKAGING, DEACTIVATED, FINAL
}
