SET
    FOREIGN_KEY_CHECKS = 0;

INSERT INTO SEQUENCE_BATCHNUMBER(seq_value)
VALUES (0);

INSERT INTO SEQUENCE_ICCID(name, seq_value)
VALUES ('DEFAULT', 10000000);

INSERT INTO SEQUENCE_MSIN(name, seq_value)
VALUES ('DEFAULT', 100000000);

SET
    FOREIGN_KEY_CHECKS = 1;
